AWSTemplateFormatVersion: "2010-09-09"
Description: 
  Network Create

Metadata: 
  "AWS::CloudFormation::Interface": 
    ParameterGroups: 
      - Label: 
          default: "Common Variable Configuration"
        Parameters: 
          - ProjectName
          - Environment

    ParameterLabels: 
      ProjectName: 
        default: "Project Name Setting"
      Environment: 
        default: "Environment Name Setting Cidr"

# ------------------------------------------------------------#
# Input Parameters
# ------------------------------------------------------------# 
Parameters:
# Common Variable
  ProjectName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prod
# # Vpc Network Variable
#   SecurityGroup:
#     Type: String

Resources: 
# ------------------------------------------------------------#
#  SecurityGroup
# ------------------------------------------------------------#
  AllSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "all-allowed-securitygroup"
      GroupName: !Sub all-allowed-securitygroup-${Environment}
      SecurityGroupIngress:
            -
              IpProtocol: -1 # 全てのプロトコルを許可
              CidrIp: 0.0.0.0/0
      VpcId: 
        Fn::ImportValue:
          !Sub ${ProjectName}-vpc-${Environment}  # VPC ID を記載

# ------------------------------------------------------------#
#  SubnetGroup
# ------------------------------------------------------------#
  AllSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "all-allowed-securitygroup"
      GroupName: !Sub all-allowed-securitygroup-${Environment}
      SecurityGroupIngress:
            -
              IpProtocol: -1 # 全てのプロトコルを許可
              CidrIp: 0.0.0.0/0
      VpcId: 
        Fn::ImportValue:
          !Sub ${ProjectName}-vpc-${Environment}  # VPC ID を記載

# ------------------------------------------------------------#
#  EC2
# ------------------------------------------------------------#
  AllSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "all-allowed-securitygroup"
      GroupName: !Sub all-allowed-securitygroup-${Environment}
      SecurityGroupIngress:
            -
              IpProtocol: -1 # 全てのプロトコルを許可
              CidrIp: 0.0.0.0/0
      VpcId: 
        Fn::ImportValue:
          !Sub ${ProjectName}-vpc-${Environment}  # VPC ID を記載

# ------------------------------------------------------------#
#  RDS
# ------------------------------------------------------------#
  AllSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "all-allowed-securitygroup"
      GroupName: !Sub all-allowed-securitygroup-${Environment}
      SecurityGroupIngress:
            -
              IpProtocol: -1 # 全てのプロトコルを許可
              CidrIp: 0.0.0.0/0
      VpcId: 
        Fn::ImportValue:
          !Sub ${ProjectName}-vpc-${Environment}  # VPC ID を記載

# ------------------------------------------------------------#
# Output Parameters
# ------------------------------------------------------------#                
# Outputs:

