AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 for LifeCycle
Parameters:
  CloudFormationTemplateBucketName:
    Type: String
    Description: CloudFormation Template Store
  ProjectName:
    Type: String
    Description: ProjectName Setting
  Environment:
    Type: String
    Description: Environment Setting

Resources:
  CloudFormationTemplateBucketStore:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub '${ProjectName}-${CloudFormationTemplateBucketName}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref CloudFormationTemplateBucketName
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
    